name: Go CI

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  go-ci:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        # v4.2.2
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Go CI
        # v1 / fd0374debcf0f9e2f90bb03797645c17f5499920
        uses: pipery-dev/golang-ci@fd0374debcf0f9e2f90bb03797645c17f5499920
        with:
          skip_versioning: 'true'
          skip_packaging: 'true'
          skip_release: 'true'
          skip_reintegration: 'true'
